services:
  frontend:
    build: ./frontend
    ports:
      - 127.0.0.1:8080:80
  backend:
    build: ./backend
    ports:
      - 127.0.0.1:8000:8000
    command: /root/.local/bin/uv run uvicorn app.main:app --host 0.0.0.0
    volumes:
      - shared-data:/data
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
  worker:
    build: ./backend
    environment:
      - CELERY_WORKER_RUNNING=1
    command: /root/.local/bin/uv run celery -A app.worker.tasks worker --pool=solo -l INFO
    volumes:
      - shared-data:/data

volumes:
  shared-data: